---
# boost version
boost:
  version: master

# product definition
product:
  name: todo
  description: Simple Todo

# openshift cluster definition
openshift:
  domain: openshift1.lab.local
  username: admin
  password: admin

# Task Manager
task_manager:
  name: trello
  title: Features

# trello
trello:
  access_token: "{{ credentials.trello.access_token }}"
  api_key: "{{ credentials.trello.api_key }}"

# couchbase
couchbase:
  user: Adminstrator
  password: password

# git definition
git:
  user: "{{ credentials.github.user }}"
  password: "{{ credentials.github.password }}"
  webhooks:
    setup: boostcd.github_webhook_setup
    teardown: boostcd.github_webhook_teardown
